In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1,2,3,6,12])
a

array([ 1,  2,  3,  6, 12])

In [7]:
a[2] = 10

In [8]:
a

array([ 1,  2, 10,  6, 12])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(2,13)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [15]:
np.linspace(0,1000,11)

array([   0.,  100.,  200.,  300.,  400.,  500.,  600.,  700.,  800.,
        900., 1000.])

## Multi-dimentional arrays

In [16]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [19]:
n[0][1]

np.int64(2)

In [20]:
n[1][2]

np.int64(6)

In [22]:
n[1,2] = 10

In [23]:
n

array([[ 1,  2,  3],
       [ 4,  5, 10],
       [ 7,  8,  9]])

In [24]:
n[1]

array([ 4,  5, 10])

In [25]:
n[2] = [1,1,1]

In [26]:
n

array([[ 1,  2,  3],
       [ 4,  5, 10],
       [ 1,  1,  1]])

In [29]:
# accessing entire column
n[:,2]

array([ 3, 10,  1])

In [30]:
n[:,2] = [111,222,333]

In [31]:
n

array([[  1,   2, 111],
       [  4,   5, 222],
       [  1,   1, 333]])

## Randomly generated arrays

In [33]:
# gives random number between 0,1
np.random.rand(5,2)

array([[0.00280357, 0.30925725],
       [0.50417373, 0.83248299],
       [0.85783464, 0.36068038],
       [0.70431765, 0.78723748],
       [0.56558132, 0.7499674 ]])

In [34]:
# gives specific seeds of random numbers(fixed results)
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [36]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [37]:
# standard normal distribution
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [38]:
# .rand ranges from 0 to 1.
# times 100 ranges from 0 to 100
np.random.seed(2)
np.random.rand(5,2) * 100

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [39]:
# low included, high excluded
np.random.seed(2)
np.random.randint(low = 0, high = 100, size = (5,2)) 

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations

In [40]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [41]:
a +1

array([1, 2, 3, 4, 5])

In [42]:
a*2

array([0, 2, 4, 6, 8])

In [44]:
b = (10 + (a*2))**2 / 100

In [45]:
a+b

array([1.  , 2.44, 3.96, 5.56, 7.24])

## Comparison operations

In [46]:
a

array([0, 1, 2, 3, 4])

In [47]:
a>=2

array([False, False,  True,  True,  True])

In [49]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [48]:
a>b

array([False, False,  True,  True,  True])

In [50]:
a[a>b]

array([2, 3, 4])

## Summarizing operations

In [51]:
a

array([0, 1, 2, 3, 4])

In [52]:
a.min()

np.int64(0)

In [53]:
a.sum()

np.int64(10)

In [54]:
a.std()

np.float64(1.4142135623730951)